### ISSUE TITLE
Some unscientific(maybe) problems...

### ISSUE THREAD

**Issue by Senorsen** [clarkok/clog#1]
https://github.com/clarkok/clog/blob/master/backend/application/models/posts_model.php
L72 Unscientific usage of 'array_slice' func in PHP or 'LIMIT' kwd in SQL. This may lead to performance problems.

**Comment by Senorsen** [comment]
done?

**Comment by clarkok** [comment]
Not yet. It may not be done until the whole project is fullly funcitonal.

Clarkok

ÔÚ 2013Äê11ÔÂ18ÈÕ 10:03:20
"notifications"notifications@github.com Ð´µÀ£º

done?

&mdash;

**Comment by Senorsen** [comment]
Okay.
Best wishes.
